### ISSUE TITLE
Project is missing sample.lua?

### ISSUE THREAD

**Issue by inhahe** [rossgoodwin/lexiconjure#1]
If I understand the program correctly, the main part of the program, the part that uses a neural network to come up with a definition, is done by a program called sample.lua, which isn't included in the project..

I'd like to adapt this project into a Limnoria plugin for my friend and me to use it in IRC, but it seems like I need sample.lua to do that.

**Comment by inhahe** [comment]
Also, it seems to run sample.lua with a program/instruction called th? I'm not sure what that is, is that a linux command? a lua interpreter? do I need th?

**Comment by rossgoodwin** [comment]
th is [torch](http://torch.ch/). This repo has 2 dependencies:
1) [Char-RNN](https://github.com/karpathy/char-rnn) by Andrej Karpathy
2) The model I trained, which I haven't released yet.

Stay tuned for #2.
